swagger: '2.0'
info:
  version: '1.0'
  title: ''
  description: ''
paths: {}
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /smart-village-app/SmartVillageServer/1.0
schemes:
 - https